### ISSUE TITLE
Consider making the `VCC` trace wider or using a wide copper shape

### ISSUE THREAD

**Issue by isobering** [oxidecomputer/hardware-adafruit-ignition-adapter#6]
Since there's room on the PCB, consider making the `VCC` trace a large copper shape/plane on the top layer.

EDIT - there's also some inconsistency with ground return vias at both ends of the `VCC` trace. There are two ground return vias on either side of `VCC` next to jumper JP1, but there aren't any ground return vias where `VCC` terminates into J2. Either we need ground return vias on both ends of the trace, or we should remove them.

I suspect that ground return vias are overkill in this design because our data rates are slow enough that the ground via/pin in J2 and the ground pin in J1 (pin 3) are sufficient. So if you want to get some layout room back, you can probably delete the ground return vias on either side of the `VCC` trace by JP2.

**Comment by nathanaelhuffman** [comment]
So most of our designs don't use any power to/from the target at all here so I think this is mostly a don't care.  I did notice some acute angles coming out of the jumper so I adjusted those to be right-angle.

![image](https://github.com/oxidecomputer/hw-ignition-adapter/assets/8078693/ae78e0d7-7258-425b-8c7f-a469ca478d30)
